# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms_sender.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10sms_sender.proto\"4\n\nSMSMessage\x12\x15\n\rmobile_number\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\tMessageID\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"E\n\rMessageStatus\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x11\n\tipaddress\x18\x03 \x01(\t2h\n\nSMSService\x12(\n\x0bSendMessage\x12\x0b.SMSMessage\x1a\n.MessageID\"\x00\x12\x30\n\x10GetMessageStatus\x12\n.MessageID\x1a\x0e.MessageStatus\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sms_sender_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SMSMESSAGE._serialized_start=20
  _SMSMESSAGE._serialized_end=72
  _MESSAGEID._serialized_start=74
  _MESSAGEID._serialized_end=99
  _MESSAGESTATUS._serialized_start=101
  _MESSAGESTATUS._serialized_end=170
  _SMSSERVICE._serialized_start=172
  _SMSSERVICE._serialized_end=276
# @@protoc_insertion_point(module_scope)
